version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: leafwheels-postgres
    environment:
      POSTGRES_DB: leafwheels
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leafwheels-net

  redis:
    image: redis:7-alpine
    container_name: leafwheels-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - leafwheels-net

  backend:
    build: .
    container_name: leafwheels-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/leafwheels
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    networks:
      - leafwheels-net

  frontend:
    build: ../frontend
    container_name: leafwheels-frontend
    ports:
      - "3000:80"
    networks:
      - leafwheels-net

volumes:
  postgres_data:
  redis_data:

networks:
  leafwheels-net:
