name: Docker CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build backend image
      run: |
        docker build -t leafwheels-backend ./leafwheels
    
    - name: Build frontend image
      run: |
        docker build -t leafwheels-frontend ./frontend
    
    - name: Start services with Docker Compose
      run: |
        docker compose up -d
    
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to start..."
        sleep 30
    
    - name: Check backend health
      run: |
        curl -f http://localhost:8080/actuator/health || \
        curl -f http://localhost:8080/api/v1/vehicles || \
        echo "Backend health check failed but continuing..."
    
    - name: Check frontend accessibility
      run: |
        curl -f http://localhost:3000 || echo "Frontend check failed but continuing..."
    
    - name: Check Redis connectivity
      run: |
        docker exec leafwheels-redis redis-cli ping
    
    - name: Check PostgreSQL connectivity
      run: |
        docker exec leafwheels-postgres pg_isready -U user -d leafwheels
    
    - name: Show container logs (on failure)
      if: failure()
      run: |
        echo "=== Backend logs ==="
        docker logs leafwheels-backend
        echo "=== Frontend logs ==="
        docker logs leafwheels-frontend
        echo "=== PostgreSQL logs ==="
        docker logs leafwheels-postgres
        echo "=== Redis logs ==="
        docker logs leafwheels-redis
    
    - name: Stop and cleanup
      if: always()
      run: |
        docker compose down -v
        docker system prune -f
